import Vue from 'vue'
import { library, config } from '@fortawesome/fontawesome-svg-core'
// fas
import {
  faSearch,
  faBell,
  faBars,
  faQuestionCircle,
  faCheck,
  faUserCircle,
  faEnvelope,
  faLock,
  faPlus,
  faTimes,
  faCamera,
  faBookmark,
  faPlay,
  faEquals,
  faStar,
  faUserFriends,
  faCommentAlt,
  faShareAlt,
  faTag,
  faSortDown,
  faCaretDown,
  faThumbsUp,
  faSearchLocation,
  faUserGraduate,
  faTools,
  faCube,
  faMapMarkerAlt,
  faBookOpen,
  faEllipsisV,
  faArrowRight,
  faArrowLeft,
  faArrowCircleLeft,
  faArrowCircleRight,
  faCaretUp,
  faCog,
  faInbox,
  faChevronRight,
  faAngleUp,
  faReply,
  faTrash,
  faBook,
  faCode,
  faExclamationCircle,
  faShoppingCart,
  faCheckCircle,
  faSortUp,
  faFile,
  faLink,
  faCaretRight,
  faEdit,
  faUser,
  faUserPlus,
  faEye,
  faDollarSign,
  faImages,
  faHotel,
  faCalendarAlt,
  faMinus,
  faGripLines,
  faLocationArrow,
  faChevronLeft,
  faExpandArrowsAlt,
  faEyeSlash,
  faMapMarkedAlt,
  faDivide,
  faPencilAlt,
  faFolderPlus
} from '@fortawesome/free-solid-svg-icons'
// far
import { faBookmark as farBookmark, faCreditCard,   
} from '@fortawesome/free-regular-svg-icons'
// fab
import { faFacebookSquare, faLine, faTwitterSquare, faLinkedin, faGithubSquare, faGoogle } from '@fortawesome/free-brands-svg-icons'

import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
// This is important, we are going to let Nuxt.js worry about the CSS
config.autoAddCss = false

// You can add your icons directly in this plugin. See other examples for how you
// can add other styles or just individual icons.
library.add(
  faEdit,
  faCode,
  faBook,
  faSearch,
  faSearchLocation,
  faBell,
  faPlus,
  faChevronLeft,
  faFolderPlus,
  faDivide,
  faQuestionCircle,
  faCheck,
  faCamera,
  faPencilAlt,
  faUserCircle,
  faEnvelope,
  faChevronRight,
  faLock,
  faLocationArrow,
  faCalendarAlt,
  faMapMarkedAlt,
  faImages,
  faTimes,
  faUserPlus,
  faEllipsisV,
  faCog,
  faShareAlt,
  faMapMarkerAlt,
  faArrowLeft,
  faArrowRight,
  faArrowCircleLeft,
  faArrowCircleRight,
  faBookmark,
  faHotel,
  faCreditCard,
  farBookmark,
  faPlay,
  faStar,
  faUserFriends,
  faCommentAlt,
  faShareAlt,
  faFacebookSquare,
  faLine,
  faTwitterSquare,
  faLinkedin,
  faTag,
  faUser,
  faMinus,
  faEye,
  faEquals,
  faCaretDown,
  faThumbsUp,
  faUserGraduate,
  faTools,
  faSortDown,
  faCube,
  faGripLines,
  faBookOpen,
  faCaretUp,
  faInbox,
  faAngleUp,
  faReply,
  faTrash,
  faDollarSign,

  faChevronLeft,
  faGithubSquare,
  faGoogle,
  faExclamationCircle,
  faShoppingCart,
  faCheckCircle,
  faSortUp,
  faFile,
  faLink,
  faCaretRight,
  faBars,
  faLink,
  faExpandArrowsAlt,
  faEyeSlash
)
// Register the component globally
Vue.component('font-awesome-icon', FontAwesomeIcon)
